# Site settings
title: 
header-img: img/home-bg.png
email: rudiakim@usc.edu
copyright_name: rudiakim
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rudiakim
learn_profile: rudiakim
email_username: rudiakim@usc.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
